name: Windows CI
on:
  workflow_dispatch

# Only run on the latest workflow run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-windows-tests:
    name: Build & run tests
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "^16"
          cache: "yarn"

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: Setup Windows SDKs
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 18362

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 17763

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '16.0'
          msbuild-architecture: x64

      - name: Install node modules
        run: yarn install

      - name: Build x64 release
        shell: powershell
        run: |
          Set-Location -Path ./apps/paper
          yarn react-native run-windows --arch x64 --sln ./windows/cppwinrt/Example.sln --proj ./windows/cppwinrt/Example.vcxproj --logging --no-autolink --no-deploy
